marker:
  template:
    path: classpath:/templates

props:
  config:
    file-store-path: ../files

spring:
  application:
    name: brand-ambasador
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://161.97.69.205:5432/brand-amb
    username: remas
    password: Pass@word1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private_key.pem
  public-key: classpath:certs/public_key.pem

google:
  client:
    id: 168068251422-e7uf2uboav5o8bfug8ldfb2l7tn0sgic.apps.googleusercontent.com

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true